
name: Test ZCU111

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: [zcu111]

    steps:
    - uses: actions/checkout@v3
    - name: Install package
      run: |
        sudo -A -E -H python -m pip install --upgrade pip
        sudo -A -E -H python -m pip install -e .
    - name: Test notebooks
      run: |
        sudo -A -E python -m pytest --nbmake --overwrite ./qick_demos/00_Send_receive_pulse.ipynb
        # sudo -E python -m pytest --nbmake ./qick_demos/01_Phase_coherent_readout.ipynb
        # sudo -E python -m pytest --nbmake ./qick_demos/02_Sweeping_variables.ipynb
        # sudo -E python -m pytest --nbmake ./qick_demos/03_Conditional_logic.ipynb
        # sudo -E python -m pytest --nbmake ./qick_demos/04_Reading_Math_Writing.ipynb
        # sudo -E python -m pytest --nbmake ./qick_demos/05_PhaseCoherence_QickProgram.ipynb
        # sudo -E python -m pytest --nbmake ./qick_demos/06_qubit_demos.ipynb
        # sudo -E python -m pytest --nbmake ./qick_demos/07_Sweep_ND_variables.ipynb
        # sudo -E python -m pytest --nbmake ./qick_demos/08_Special_buffers.ipynb
    - name: Cleanup pytest cache
      if: always()
      run: |
        sudo -A rm -d -r -f ./.pytest_cache
        sudo -A rm -d -r -f ./qick_lib/qick.egg-info
        sudo -A rm -d -r -f ./qick_lib/qick/__pycache__
        sudo -A rm -d -r -f ./qick_lib/qick/drivers/__pycache__
