# Install the QICK library on the runner (a QICK board) and run tests.
# The FPGA can only be accessed as root, so the tests must run with sudo.
# This pollutes the repo with files owned by root, which interfere with the "clean" step in the checkout action.
# We therefore do the clean manually (with sudo) before checkout.

name: Test ZCU111

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'qick_demos/**'
      - 'qick_lib/**'
      - '**.py'
  
permissions:
  contents: write

jobs:
  run_test:
    runs-on: [zcu111]
    steps:
    - name: Clean repo
      continue-on-error: true
      run: |
        sudo git clean -ffdx
        sudo git reset --hard HEAD
    - uses: actions/checkout@v4
    - name: Install package
      run: |
        sudo -E -H python -m pip install -e .
    - name: Test notebooks
      run: |
        sudo -E python -m pytest --nbmake --overwrite ./qick_demos/00_Send_receive_pulse.ipynb
        sudo -E python -m pytest --nbmake ./qick_demos/01_Phase_coherent_readout.ipynb
        sudo -E python -m pytest --nbmake ./qick_demos/02_Sweeping_variables.ipynb
        sudo -E python -m pytest --nbmake ./qick_demos/03_Conditional_logic.ipynb
        sudo -E python -m pytest --nbmake ./qick_demos/04_Reading_Math_Writing.ipynb
        sudo -E python -m pytest --nbmake ./qick_demos/05_PhaseCoherence_QickProgram.ipynb
        # sudo -E python -m pytest --nbmake ./qick_demos/06_qubit_demos.ipynb
        sudo -E python -m pytest --nbmake ./qick_demos/07_Sweep_ND_variables.ipynb
        sudo -E python -m pytest --nbmake ./qick_demos/08_Special_buffers.ipynb
    - name: Archive test results
      uses: actions/upload-artifact@v4
      with:
        name: demo_notebooks
        path: qick_demos/*.ipynb
